LINK_STATES = {
    0x0000: "not init",
    0x00FF: "initializing",
    0x0100: "idle",
    0x0200: "silent",
    0x0300: "handshake",
    0x0380: "full init",
    0x03c0: "short init",
    0x0400: "discover",
    0x0500: "training",
    0x0800: "showtime",
    0x0801: "showtime",
    0x0900: "fast retrain",
    0x0b00: "diagnosis active",
    0x0c00: "diagnosis complete",
}

SENSORS = {
    "US current actual data rate": {
        "name": "US Current Data Rate",
        "unit_of_measurement": "kbit/s",
        "device_class": "data_rate",
        "icon": "upload",
        "type": int,
    },
    "DS current actual data rate": {
        "name": "DS Current Data Rate",
        "unit_of_measurement": "kbit/s",
        "device_class": "data_rate",
        "icon": "download",
        "type": int,
    },
    "DSL training mode": {
        "name": "DSL Training Mode",
        "unit_of_measurement": None,
        "icon": "call-merge",
        "entity_category": "diagnostic",
        "type": str,
    },
    "DSL link state": {
        "name": "DSL Link State",
        "unit_of_measurement": None,
        "icon": "sync",
        "diagnostic": False,
        "type": hex,
        "convert": LINK_STATES,
    },
    "US attainable data rate": {
        "name": "Upstream Attainable Data Rate",
        "unit_of_measurement": "kbit/s",
        "device_class": "data_rate",
        "icon": "upload-outline",
        "entity_category": "diagnostic",
        "type": int,
    },
    "DS attainable data rate": {
        "name": "Downstream Attainable Data Rate",
        "unit_of_measurement": "kbit/s",
        "device_class": "data_rate",
        "icon": "download-outline",
        "entity_category": "diagnostic",
        "type": int,
    },
    "US SNR margin": {
        "name": "Upstream SNR Margin",
        "unit_of_measurement": "dB",
        "icon": "waveform",
        "entity_category": "diagnostic",
        "type": float,
    },
    "DS SNR margin": {
        "name": "Downstream SNR Margin",
        "unit_of_measurement": "dB",
        "icon": "waveform",
        "entity_category": "diagnostic",
        "type": float,
    },
    "Link detected": {
        "name": "ETH Connected",
        "unit_of_measurement": None,
        "icon": "ethernet-cable",
        "entity_category": "diagnostic",
        "type": str,
        "convert": {
            "yes": "on",
            "no": "off",
        }
    },
    "near-end xDSL FEC anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "near-end xDSL CV/CRC-8 anomalies": {
        "name": "near-end xDSL CV-CRC-8 anomalies",
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "near-end ATM HEC anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "near-end ATM Rx user cells": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "near-end ATM Tx user cells": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "near-end PTM CRC-n anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "near-end PTM CRC-np anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "near-end PTM CV-n anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "near-end PTM CV-np anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "far-end xDSL FEC anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "far-end xDSL CV/CRC-8 anomalies": {
        "name": "far-end xDSL CV-CRC-8 anomalies",
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "far-end ATM HEC anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "far-end ATM Rx user cells": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "far-end ATM Tx user cells": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "far-end PTM CRC-n anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "far-end PTM CRC-np anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "far-end PTM CV-n anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "far-end PTM CV-np anomalies": {
        "icon": "timeline-alert-outline",
        "entity_category": "diagnostic",
        "state_class": "total_increasing",
        "type": int,
    },
    "US line attenuation": {
        "icon": "slope-downhill",
        "entity_category": "diagnostic",
        "type": float,
        "unit_of_measurement": "dB",
    },
    "US signal attenuation": {
        "icon": "slope-downhill",
        "entity_category": "diagnostic",
        "type": float,
        "unit_of_measurement": "dB",
    },
    "DS line attenuation": {
        "icon": "slope-downhill",
        "entity_category": "diagnostic",
        "type": float,
        "unit_of_measurement": "dB",
    },
    "DS signal attenuation": {
        "icon": "slope-downhill",
        "entity_category": "diagnostic",
        "type": float,
        "unit_of_measurement": "dB",
    },
    "Modem Uptime": {
        "icon": "timer-outline",
        "entity_category": "diagnostic",
        # "device_class":
        "type": float,
        "unit_of_measurement": "s",
        "internal": True,
    },
}